[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "e680eddabfdf73d610409f162f3f37dedd324cc6"
os = "macos"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "9376b0698728185c7808069bd6d976f1ce9c3d913c5c1af7a47f4d0ceb7015f1"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "36fc0067d1bdc4640fbd7982a7d082dd178c5d17"
libc = "glibc"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "a08a4b4ab1a3ffd99561de4b3c6535631fe5642a9758a8b1c9c47b448a9b36eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "b010832a5b4da727feaac11cd645cf13a0406979"
libc = "musl"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "6e40026dab2687a4cebcc5c943153dead18ea21b2ff977d5a2faab4e61f8a8c9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.aarch64-linux-musl.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "998baddad706de2123e955bbf08e043d1d7a88db"
os = "freebsd"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "1b8c80797afd283597386a6b150d9d1059e1fa86b5c05747ec3d8ad680e67a5c"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "powerpc64le"
git-tree-sha1 = "83093597a41cc8cc448249583c836903c675b53d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "69267fdf7aa8c2d1ee15544606fb06d89aa264942998f3a1414c3f20740dc8ed"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "67e2a8b987c7efe2d7269debaccffc3257760308"
os = "macos"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "0fe91907c51f336200318b54bf8c83b9740f23a81970ed211c07db34c017b0e9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "e8f8c2e413923a8e756d8695e206c0042890f23d"
libc = "glibc"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "c1e703c7235631288dd407e58fa8ff0f4ccb67f9ec3ecc6c2e4d01efa64a43e9"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "09c797c977b481fd32c18c74618acadc23276951"
libc = "musl"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "5c4685786567cc88ba5012299bba92d164d3b24f02d5c2a618f866f284d647d4"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.x86_64-linux-musl.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "8d830d1fcd80b7f6cd8790f5b2844c3db829d8c2"
os = "freebsd"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "356536c85d69549aac19f806fc06c538b11739be4ae791e8a503106b2721688a"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.701+0/GAP_pkg_caratinterface.v200.300.701.x86_64-unknown-freebsd.tar.gz"
