[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "886620443f92a1d8c22fdb1e198deb8b0086634e"
os = "macos"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "af737ea9aabe903c359f22d9f88ebd913916d38cdd074a88bb1516daadb7881d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.aarch64-apple-darwin.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "4ee7f85498316bdea9c79a800bad2a7825e3db18"
libc = "glibc"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "99b1d0c7b1543eac21d6eee8c6b4b29df79ea9689da3320082b8bc21675743f3"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.aarch64-linux-gnu.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "474d12fc6ad791a91ac5eeb013f03ef6d29d300f"
libc = "musl"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "b6e9739697b7d0d7e489c7af62e63b1d8a2457edf7fc7e6c328ff080de86cda5"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.aarch64-linux-musl.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "aarch64"
git-tree-sha1 = "086fd6d8153368b65a11fbe304d9fa77a63577fb"
os = "freebsd"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "0b73ace35b27cf60f6cdf8c2f02e16c6eae969f03aa153d59e79bfb668702b9d"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.aarch64-unknown-freebsd.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "powerpc64le"
git-tree-sha1 = "0ae0b4c8c91adbad4d29bb9de5c07ed35934b664"
libc = "glibc"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "0a39f20173f2d84f6705a94df6b2b55199cde1bc7a0ffc77340238fec33983eb"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.powerpc64le-linux-gnu.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "c34cb6079da4a32c8d191b401cf665ed543f7f30"
os = "macos"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "300e1e84cb9a087576beff7f8aba1391a5c97f5e68294a683747b878cdc46758"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.x86_64-apple-darwin.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "6c90c4bcca83b03f0b698cf93da2f4fcbea659e2"
libc = "glibc"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "8c22dd6508cc0b50f90e128b58c17c28e6dad0fd65009f8866dd4d76945c4baa"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.x86_64-linux-gnu.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "deb5cd5e42763da38940e28db956f4e37615a07c"
libc = "musl"
os = "linux"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "b6fa42fb2bba5516009b3d9037743b5f5b8f738f253b2f0bb7ebf08d6dddb817"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.x86_64-linux-musl.tar.gz"
[[GAP_pkg_caratinterface]]
arch = "x86_64"
git-tree-sha1 = "bb1e878ca64a2cc8705ba23ff920b5269a1a701f"
os = "freebsd"

    [[GAP_pkg_caratinterface.download]]
    sha256 = "c1fdc0111f8ad58589f0231a9c2537d57635dece58ed256a362571c1f1786c43"
    url = "https://github.com/JuliaBinaryWrappers/GAP_pkg_caratinterface_jll.jl/releases/download/GAP_pkg_caratinterface-v200.300.700+0/GAP_pkg_caratinterface.v200.300.700.x86_64-unknown-freebsd.tar.gz"
